[package]
name = "unnamedGame"
version = "0.0.0"
authors = ["FIXME-DOCS(Krey): authors"]
# NOTE(Krey): Not designed for release as crate
publish = false
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.9.1"
